

-- 코드를 입력하세요

SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1; # LIMIT -> 개수를 1개로 제한
#WHERE MIN(YEAR(DATETIME)); 이렇게는 사용 못한다.


-- SUBQUERY를 이용한 풀이

#SELECT NAME FROM ANIMAL_INS
#WHERE DATETIME = (SELECT MIN(DATETIME) FROM ANIMAL_INS);
